name: "Run Tests Android"
description: "Run Android tests in Firebase Test Lab"
inputs:
  module:
    required: true
  gcloud_auth:
    required: true

runs:
  using: "composite"
  steps:
    - name: 'Authenticate to Google Cloud'
      uses: google-github-actions/auth@v3
      with:
        credentials_json: ${{ inputs.gcloud_auth }}
    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v3

    # Download test apk
    - name: Download Artifacts
      uses: actions/download-artifact@v8
      id: download
      with:
        name: ${{ inputs.module }}-androidTest.apk

    - name: Instrumentation Tests (${{ inputs.module }})
      id: run_firebase
      shell: bash
      env:
        ANDROID_TEST_LOCATION: ${{ steps.download.outputs.download-path }}/${{ inputs.module }}-androidTest.apk
        DEVICE_MODEL: SmallPhone.arm,version=35
      run: >
        gcloud firebase test android run
        --type instrumentation
        --app $ANDROID_TEST_LOCATION
        --test $ANDROID_TEST_LOCATION
        --device model=$DEVICE_MODEL
        --results-bucket=pdfmp-firebase-test
        --results-dir="run-${{ github.run_id }}"
        --no-record-video