name: Test & Publish

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  release:
    types: [created]

permissions:
  contents: read
  checks: write
  pull-requests: write
  packages: write

jobs:
  test:
    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'release'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Run Tests Linux
        if: runner.os == 'Linux'
        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=linuxX64

      - name: Run Tests Windows
        if: runner.os == 'Windows'
        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=mingwX64

      - name: Run Tests MacOS
        if: runner.os == 'macOS'
        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=iosSimulatorArm64,macosArm64

      - name: Save PR number
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > pr_number.txt

      - name: Upload PR number
        if: github.event_name == 'pull_request' && matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v7
        with:
          name: pr-number
          path: pr_number.txt
      - name: Upload Test Results (macOS)
        if: runner.os == 'macOS' # Upload macos and ios separately
        uses: actions/upload-artifact@v7
        with:
          name: test-report-macos
          path: |
            **/build/test-results/macos*Test/*.xml
            **/build/test-results/jvmTest/*.xml
      - name: Upload Test Results (iOS)
        if: runner.os == 'macOS' # Upload macos and ios separately
        uses: actions/upload-artifact@v7
        with:
          name: test-report-ios
          path: '**/build/test-results/ios*Test/*.xml'
      - name: Upload Test Results (non-apple)
        if: runner.os != 'macOS' # Upload macos and ios separately
        uses: actions/upload-artifact@v7
        with:
          name: test-report-${{ matrix.os }}
          path: '**/build/test-results/**/*.xml'
      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report-${{ matrix.os }}
          path: '**/build/jacocoReports/jacocoTestReport/jacocoTestReport.xml'

  publish:
    needs: test # Only publish if tests pass
    if: github.event_name == 'release'
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - id: get_version
        name: Get version
        uses: jannemattila/get-version-from-tag@v4

      - name: Publish to Maven Repository
        run: |
          VERSION=$(echo "${{ steps.get_version.outputs.version }}")
          ./gradlew \
            :pdfmp:publishAndReleaseToMavenCentral \
            :pdfmp-compose:publishAndReleaseToMavenCentral \
            -Pversion=$VERSION \
            --build-cache \
            --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}