name: Test

on:
  push:
    branches:
      - main
      - develop
  pull_request_target:
    branches:
      - main
      - develop
  release:
    types: [created]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > pr_number.txt
      - name: Upload PR number
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: pr-number.txt
          path: pr_number.txt
          archive: false


  # pull_request_target note:
  # in build steps we checkout the code so it's a dangerous environment.
  # Don't give any permissions except contents: read.

  test-linux:
    name: Linux x64
    if: github.event_name == 'push' || github.event_name == 'pull_request_target' || github.event_name == 'release'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: ./.github/actions/build-setup
      - name: Run Tests
        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=linuxX64 -Pdebug=true

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report-ubuntu-latest
          path: ./**/build/test-results/**/*.xml

      # Build and upload APKs for instrumented testing.
      - name: Build Android Test
        run: |
          ./gradlew pdfmp:assembleAndroidDeviceTest pdfmp-compose:assembleAndroidDeviceTest\
            -PnativeTargets=androidNativeArm64 -Pdebug=true
      - name: Upload Android Test APK (pdfmp)
        uses: actions/upload-artifact@v7
        with:
          name: pdfmp-test.apk
          archive: false
          path: 'pdfmp-compose/build/outputs/apk/androidTest/pdfmp-compose-androidTest.apk'
      - name: Upload Android Test APK (pdfmp-compose)
        uses: actions/upload-artifact@v7
        with:
          name: pdfmp-compose-test.apk
          archive: false
          path: 'pdfmp/build/outputs/apk/androidTest/pdfmp-androidTest.apk'

  test-windows:
    name: Windows x64
    permissions:
      contents: read
    #    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'release'
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: ./.github/actions/build-setup
      - name: Run Tests
        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=mingwX64 -Pdebug=true
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report-windows-latest
          path: ./**/build/test-results/**/*.xml

  test-macos:
    name: macOS Arm
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run Tests macOS
        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=iosSimulatorArm64,macosArm64 -Pdebug=true
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report-macos-latest
          path: ./**/build/test-results/**/*.xml

  test-android-pdfmp:
    name: Android (pdfmp)
    runs-on: ubuntu-latest
    needs: test-linux
    continue-on-error: true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
      - name: Test pdfmp
        continue-on-error: true
        uses: ./.github/actions/test-android
        with:
          module: pdfmp
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report-ubuntu-android-pdfmp
          path: ./**/build/test-results/**/*.xml

  test-android-pdfmp-compose:
    name: Android (pdfmp-compose)
    runs-on: ubuntu-latest
    needs: test-linux
    continue-on-error: true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
      - name: Test pdfmp-compose
        uses: ./.github/actions/test-android
        continue-on-error: true
        with:
          module: pdfmp-compose
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-report-ubuntu-android-pdfmp-compose
          path: ./**/build/test-results/**/*.xml


  test-results:
    needs:
     - test-linux
     - test-macos
     - test-windows
     - test-android-pdfmp
     - test-android-pdfmp-compose
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
      - name: Download Artifacts
        uses: actions/download-artifact@v8
      - name: Test Report
        uses: dshatz/testballoon-github-reporter@master
        with:
          reports: "test-report-*/**/*.xml"
          platform-hints: |
            {
              "test-report-ubuntu-latest/**/*.xml": "Linux",
              "test-report-windows-latest/**/*.xml": "Windows",
              "test-report-macos-latest/**/*.xml": "macOS",
              "test-report-ubuntu-android-*/**/*.xml": "Android"
            }
