name: Verify

on:
  push:
    branches:
      - main
      - develop
  pull_request_target:
    branches:
      - main
      - develop
  release:
    types: [created]

#permissions:
#  contents: read
#  checks: write
#  pull-requests: write
#  packages: write
#  id-token: write # Required for WIF

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        if: github.event_name == 'pull_request'
        run: echo ${{ github.event.number }} > pr_number.txt
      - name: Upload PR number
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v7
        with:
          name: pr-number.txt
          path: pr_number.txt
          archive: false


  # pull_request_target note:
  # in build steps we checkout the code so it's a dangerous environment.
  # Don't give any permissions except contents: read.

  test-linux:
    name: Test Linux x64
    if: github.event_name == 'push' || github.event_name == 'pull_request_target' || github.event_name == 'release'
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: ./.github/actions/build-setup
      - name: Run Tests
        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=linuxX64
      - name: Upload
        uses: ./.github/actions/upload-test-results
        with:
          platform: linuxX64
      - name: Build Android Test
        run: |
          ./gradlew pdfmp:assembleAndroidDeviceTest pdfmp-compose:assembleAndroidDeviceTest\
            -PnativeTargets=androidNativeArm64

      - name: Upload Android Test APK (pdfmp)
        uses: actions/upload-artifact@v7
        with:
          name: pdfmp-test.apk
          archive: false
          path: 'pdfmp-compose/build/outputs/apk/androidTest/pdfmp-compose-androidTest.apk'
      - name: Upload Android Test APK (pdfmp-compose)
        uses: actions/upload-artifact@v7
        with:
          name: pdfmp-compose-test.apk
          archive: false
          path: 'pdfmp/build/outputs/apk/androidTest/pdfmp-androidTest.apk'

  test-windows:
    name: Test Windows x64
    permissions:
      contents: read
    #    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'release'
    if: false
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup
        uses: ./.github/actions/build-setup
      - name: Run Tests
        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=mingwX64
      - name: Upload
        uses: ./.github/actions/upload-test-results
        with:
          platform: linuxX64

  test-android-pdfmp:
    name: Test Android (Firebase)
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
      - name: Test pdfmp
        uses: ./.github/actions/test-android
        with:
          module: pdfmp
      - name: Upload results
        uses: ./.github/actions/upload-test-results
        with:
          platform: android-pdfmp

  test-android-pdfmp-compose:
    name: Test Android (Firebase)
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github/actions
      - name: Test pdfmp-compose
        uses: ./.github/actions/test-android
        with:
          module: pdfmp-compose
      - name: Upload results
        uses: ./.github/actions/upload-test-results
        with:
          platform: android-pdfmp-compose


#  test:
#    name: Tests on ${{ matrix.os }}
#    if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'release'
#    runs-on: ${{ matrix.os }}
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ macos-latest, ubuntu-latest, windows-latest ]
#    steps:
#      - name: Setup
#        uses: .github/actions/build-setup
#
#      - name: Run Tests Linux
#        if: runner.os == 'Linux'
#        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=linuxX64
#
#      - name: Run Tests Android
#        uses: ./.github/actions/test-android
#        with:
#
#
#      - name: Run Tests Windows
#        if: runner.os == 'Windows'
#        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=mingwX64
#
#      - name: Run Tests MacOS
#        if: runner.os == 'macOS'
#        run: ./gradlew jacocoTestReport --stacktrace -PnativeTargets=iosSimulatorArm64,macosArm64
#
#      - name: Upload Test Results (macOS)
#        if: runner.os == 'macOS' # Upload macos and ios separately
#        uses: actions/upload-artifact@v7
#        with:
#          name: test-report-macos
#          path: |
#            **/build/test-results/macos*Test/*.xml
#            **/build/test-results/jvmTest/*.xml
#      - name: Upload Test Results (iOS)
#        if: runner.os == 'macOS' # Upload macos and ios separately
#        uses: actions/upload-artifact@v7
#        with:
#          name: test-report-ios
#          path: '**/build/test-results/ios*Test/*.xml'
#      - name: Upload Test Results (non-apple)
#        if: runner.os != 'macOS' # Upload macos and ios separately
#        uses: actions/upload-artifact@v7
#        with:
#          name: test-report-${{ matrix.os }}
#          path: '**/build/test-results/**/*.xml'
#      - name: Upload Coverage Report
#        if: always()
#        uses: actions/upload-artifact@v7
#        with:
#          name: coverage-report-${{ matrix.os }}
#          path: '**/build/jacocoReports/jacocoTestReport/jacocoTestReport.xml'