name: Test Results

permissions:
    checks: write
    statuses: write
    pull-requests: write
    contents: read

on:
  workflow_run:
    workflows: ["Verify"]
    types: [completed]
  workflow_dispatch:
    inputs:
      manual_run_id:
        description: Manual Test Run ID
        required: true

jobs:
  test-results-linux:
    if: github.event.workflow_run.conclusion != 'cancelled'
    uses: ./.github/workflows/test-reporter.yml
    with:
      platform_name: Linux x64
      artifact_name: test-report-linuxX64
      test_run_id: ${{ github.event.inputs.manual_run_id || github.event.workflow_run.id }}
    secrets: inherit
  test-results-windows:
    if: github.event.workflow_run.conclusion != 'cancelled'
    uses: ./.github/workflows/test-reporter.yml
    with:
      platform_name: Windows x64
      artifact_name: test-report-linuxX64
      test_run_id: ${{ github.event.inputs.manual_run_id || github.event.workflow_run.id }}
    secrets: inherit
  test-results-macos:
    if: github.event.workflow_run.conclusion != 'cancelled'
    uses: ./.github/workflows/test-reporter.yml
    with:
      platform_name: macOS ARM
      artifact_name: test-report-macosArm
      test_run_id: ${{ github.event.inputs.manual_run_id || github.event.workflow_run.id }}
    secrets: inherit
  test-results-ios:
    if: github.event.workflow_run.conclusion != 'cancelled'
    uses: ./.github/workflows/test-reporter.yml
    with:
      platform_name: iOS Simulator
      artifact_name: test-report-ios
      test_run_id: ${{ github.event.inputs.manual_run_id || github.event.workflow_run.id }}
    secrets: inherit

  publish-coverage:
    # Only run if after a PR.
    if: github.event.workflow_run.conclusion != 'cancelled'
    runs-on: ubuntu-latest
    permissions:
      checks: write
      statuses: write
      pull-requests: write
      contents: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ inputs.test_run_id }}
      - name: Get PR Number
        id: get_pr
        continue-on-error: true
        run: |
          PR_NUMBER=$(cat pr-number/pr_number.txt)
          echo "nr=$PR_NUMBER" >> $GITHUB_OUTPUT
      - name: Generate Coverage Summary
        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.1
        with:
          reports: "**/jacocoTestReport.xml"
          targetdir: "coveragereport"
          reporttypes: 'MarkdownSummaryGithub'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        continue-on-error: true
        with:
          issue-number: ${{ steps.get_pr.outputs.nr }}
          body-path: coveragereport/SummaryGithub.md