name: Publish Results

on:
  workflow_run:
    workflows: ["Test & Publish"]
    types: [completed]

jobs:
  publish-test-results:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'cancelled'
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Get PR Number
        id: get_pr
        run: |
          PR_NUMBER=$(cat pr-number/pr_number.txt)
          echo "nr=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Publish Linux Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          event_file: event_file/event.json
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          files: "test-report-ubuntu-latest/**/*.xml"

      - name: Publish Windows Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          event_file: event_file/event.json
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          files: "test-report-windows-latest/**/*.xml"

      - name: Publish MacOS Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          event_file: event_file/event.json
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          files: "test-report-macos/**/*.xml"

      - name: Publish iOS Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          event_file: event_file/event.json
          commit: ${{ github.event.workflow_run.head_sha }}
          event_name: ${{ github.event.workflow_run.event }}
          files: "test-report-ios/**/*.xml"

      - name: Generate Coverage Summary
        uses: danielpalme/ReportGenerator-GitHub-Action@5.5.1
        with:
          reports: "**/jacocoTestReport.xml"
          targetdir: "coveragereport"
          reporttypes: 'MarkdownSummaryGithub'

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ steps.get_pr.outputs.nr }}
          body-path: coveragereport/SummaryGithub.md