name: "Upload test results"
inputs:
  platform:
    required: true
  kotlinTarget:
    requred: true
runs:
  using: "composite"
  steps:
    - name: Upload Test Results (${{ inputs.platform }})
      uses: actions/upload-artifact@v7
      with:
        name: test-report-${{ inputs.platform }}
        path: |
          **/build/test-results/${{inputs.kotlinTarget}}Test/*.xml
          android-results/**/*.xml